# Generated by Django 4.2 on 2023-05-01 08:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('sort_description', models.CharField(max_length=300, null=True)),
                ('description', models.TextField()),
                ('regular_proce', models.DecimalField(decimal_places=3, max_digits=10)),
                ('sale_proce', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('SKU', models.CharField(max_length=150)),
                ('stock_status', models.CharField(choices=[('IN', 'instock'), ('out', 'outofstock')], max_length=150)),
                ('feature', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=10)),
                ('imagesname', models.CharField(max_length=150)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
