# Generated by Django 4.2 on 2023-05-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='regular_proce',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_proce',
        ),
        migrations.AlterField(
            model_name='product',
            name='imagesname',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
