# Generated by Django 4.2 on 2023-05-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='tex',
        ),
    ]
