# Generated by Django 4.2 on 2023-05-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagesname',
            field=models.ImageField(upload_to='static/assets/images/products'),
        ),
    ]
