# Generated by Django 4.2 on 2023-05-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_imagesname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagesname',
            field=models.ImageField(upload_to='images/products'),
        ),
    ]
