# Generated by Django 4.2 on 2023-05-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_imagesname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_status',
            field=models.CharField(choices=[('instock', 'instock'), ('instock', 'instock')], max_length=150),
        ),
    ]
