# Generated by Django 4.2 on 2023-05-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_stock_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('link', models.CharField(max_length=100)),
                ('images', models.ImageField(upload_to='images/slider')),
                ('status', models.BooleanField()),
            ],
        ),
    ]
