# Generated by Django 4.2 on 2023-05-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_homeslider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeslider',
            name='status',
        ),
    ]
