# Generated by Django 4.2 on 2023-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')])),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
