# Generated by Django 4.2 on 2023-05-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_alter_sale_sale_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sale_date',
            new_name='saledate',
        ),
    ]
