# Generated by Django 4.2 on 2023-05-17 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('fixed', 'fixed'), ('percent', 'percent')], max_length=100)),
                ('value', models.DecimalField(decimal_places=0, max_digits=5)),
                ('cart_value', models.DecimalField(decimal_places=0, max_digits=7)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
