# Generated by Django 4.2 on 2023-05-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='cart_value',
        ),
        migrations.AddField(
            model_name='coupons',
            name='minimum_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
