# Generated by Django 4.2 on 2023-05-19 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_coupons_cart_value_coupons_minimum_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.coupons'),
        ),
    ]
