# Generated by Django 4.2 on 2023-05-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_cart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
